# -*- coding: utf-8 -*-
"""day4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjJo6Gl95FlLAmSsSrXYRtlyNr9SpRcj
"""

import os, getpass

# Paste your key here between the quotes (easiest), or leave it empty to use Colab Secrets / a prompt
API_KEY = ""

# Model name. If Google retires it, the error message names the replacement - change it here.
MODEL = "gemini-3.8-flash"

if not API_KEY:
    try:
        from google.colab import userdata
        API_KEY = userdata.get('GOOGLE_API_KEY')
    except Exception:
        API_KEY = getpass.getpass('Paste your Gemini API key: ')

API_KEY = API_KEY.strip().strip('"').strip("'")   # remove spaces/quotes/newlines
os.environ['GOOGLE_API_KEY'] = API_KEY
print('Key length:', len(API_KEY))

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model=MODEL)
print('LLM ready, model =', MODEL)

from typing import TypedDict

class State(TypedDict):
    question: str   # input
    category: str   # technical / billing / general
    thinking: str   # chain of thought
    answer: str     # final reply

def ask(prompt):
    # newer Gemini models may return a list of blocks; this always gives plain text
    content = llm.invoke(prompt).content
    if isinstance(content, list):
        return ''.join(b if isinstance(b, str) else b.get('text', '') for b in content)
    return content

def classify(state):
    text = ask('Reply with ONE word: technical, billing or general.\n' + state['question'])
    word = text.strip().lower()
    if word not in ['technical', 'billing', 'general']:
        word = 'general'
    return {'category': word}

def think(state):
    text = ask('Think step by step in 3 short numbered steps about how to solve this:\n' + state['question'])
    return {'thinking': text}

def reply(state, role):
    prompt = f"You are a {role}. Using these steps, answer in 3 short sentences.\nSteps: {state['thinking']}\nCustomer: {state['question']}"
    return ask(prompt)

def technical(state):
    return {'answer': reply(state, 'technical support engineer')}

def billing(state):
    return {'answer': reply(state, 'billing specialist')}

def general(state):
    return {'answer': reply(state, 'customer care agent')}

def router(state):
    return state['category']

from langgraph.graph import StateGraph, START, END

g = StateGraph(State)

g.add_node('classify', classify)
g.add_node('think', think)
g.add_node('technical', technical)
g.add_node('billing', billing)
g.add_node('general', general)

g.add_edge(START, 'classify')
g.add_edge('classify', 'think')
g.add_conditional_edges('think', router, ['technical', 'billing', 'general'])
g.add_edge('technical', END)
g.add_edge('billing', END)
g.add_edge('general', END)

app = g.compile()

from IPython.display import Image, display
try:
    display(Image(app.get_graph().draw_mermaid_png()))
except Exception:
    print(app.get_graph().draw_mermaid())

import time

def run(question):
    start = time.time()
    state = {'question': question}
    for update in app.stream(state):      # shows each step as soon as it finishes
        for node, values in update.items():
            print(f'[{time.time() - start:5.1f}s] {node} done')
            state.update(values)
    print('CATEGORY :', state['category'])
    print('THINKING :\n', state['thinking'])
    print('ANSWER   :', state['answer'])
    print('null' * 60)

run('I was chargedtwice this month.')

# Run these one at a time when you want (each takes a few more seconds):
# run('I was charged twice this month.')
# run('What are your support hours?')

import os, getpass, subprocess, sys

# Auto-install anything missing (so it works even if the pip cell above was skipped)
try:
    import langgraph, langchain_google_genai, langchain_groq
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
                           'langgraph', 'langchain-google-genai', 'langchain-groq'])

# Paste keys between the quotes (easiest), or leave empty to use Colab Secrets / a prompt
GOOGLE_API_KEY = ""
GROQ_API_KEY = ""

def get_key(value, secret_name):
    if not value:
        try:
            from google.colab import userdata
            value = userdata.get(secret_name)
        except Exception:
            value = getpass.getpass('Paste your ' + secret_name + ': ')
    return value.strip().strip('"').strip("'")

os.environ['GOOGLE_API_KEY'] = get_key(GOOGLE_API_KEY, 'GOOGLE_API_KEY')
os.environ['GROQ_API_KEY'] = get_key(GROQ_API_KEY, 'GROQ_API_KEY')

# Model names. Leave MODEL_B / JUDGE_MODEL as "" to auto-pick from what YOUR Groq key can use.
# Or type a model name to force it.
MODEL_A = "gemini-3.8-flash"   # Google Gemini
MODEL_B = ""                   # contestant from Groq (auto: prefers Llama)
JUDGE_MODEL = ""               # judge from Groq (auto: a different model than MODEL_B)

# Ask Groq which models this key can actually use
try:
    from groq import Groq
    available = sorted(m.id for m in Groq().models.list().data)
except Exception as e:
    available = []
    print('Could not list Groq models:', str(e)[:150])

skip = ('whisper', 'orpheus', 'guard', 'tts', 'safeguard', 'embed')
chat_models = [m for m in available if not any(s in m for s in skip)]
print('Groq chat models available to your key:', chat_models)

def pick(preferred, avoid=None):
    for m in preferred:
        if m in chat_models and m != avoid:
            return m
    for m in chat_models:
        if m != avoid:
            return m
    return None

if not MODEL_B:
    MODEL_B = pick(['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'openai/gpt-oss-20b']) or 'llama-3.3-70b-versatile'
if not JUDGE_MODEL:
    JUDGE_MODEL = pick(['openai/gpt-oss-120b', 'llama-3.3-70b-versatile', 'openai/gpt-oss-20b'], avoid=MODEL_B) or MODEL_B

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq

llm_a = ChatGoogleGenerativeAI(model=MODEL_A, timeout=30, max_retries=1)
llm_b = ChatGroq(model=MODEL_B, timeout=30, max_retries=1)
llm_judge = ChatGroq(model=JUDGE_MODEL, timeout=30, max_retries=1)
print('Ready:', MODEL_A, '|', MODEL_B, '| judge:', JUDGE_MODEL)

!pip install -q langgraph langchain-google-genai langchain-groq

import os, getpass

# Paste keys between the quotes (easiest), or leave empty to use Colab Secrets / a prompt
GOOGLE_API_KEY = ""
GROQ_API_KEY = ""

def get_key(value, secret_name):
    if not value:
        try:
            from google.colab import userdata
            value = userdata.get(secret_name)
        except Exception:
            value = getpass.getpass('Paste your ' + secret_name + ': ')
    return value.strip().strip('"').strip("'")

os.environ['GOOGLE_API_KEY'] = get_key(GOOGLE_API_KEY, 'GOOGLE_API_KEY')
os.environ['GROQ_API_KEY'] = get_key(GROQ_API_KEY, 'GROQ_API_KEY')

# Model names - change here if a model is retired
MODEL_A = "gemini-3.8-flash"            # Google Gemini
MODEL_B = "llama-3.3-70b-versatile"     # Meta Llama, served by Groq
JUDGE_MODEL = "openai/gpt-oss-120b"     # a third model judges, so no contestant judges itself

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq

llm_a = ChatGoogleGenerativeAI(model=MODEL_A, timeout=30, max_retries=1)
llm_b = ChatGroq(model=MODEL_B, timeout=30, max_retries=1)
llm_judge = ChatGroq(model=JUDGE_MODEL, timeout=30, max_retries=1)
print('Ready:', MODEL_A, '|', MODEL_B, '| judge:', JUDGE_MODEL)

from typing import TypedDict

class State(TypedDict):
    question: str   # input
    answer_a: str   # answer from model A
    answer_b: str   # answer from model B
    time_a: float   # seconds model A took
    time_b: float   # seconds model B took
    winner: str     # 'a' or 'b'
    reason: str     # why the judge chose it
    final: str      # the best answer

import time, re, random

def ask(llm, prompt):
    # always returns plain text (some models return a list of blocks)
    content = llm.invoke(prompt).content
    if isinstance(content, list):
        return ''.join(b if isinstance(b, str) else b.get('text', '') for b in content)
    return content

def run_model(llm, question):
    start = time.time()
    try:
        text = ask(llm, question)
    except Exception as e:
        text = 'ERROR: ' + str(e)[:200]
    return text, round(time.time() - start, 1)

def model_a(state):
    text, secs = run_model(llm_a, state['question'])
    return {'answer_a': text, 'time_a': secs}

def model_b(state):
    text, secs = run_model(llm_b, state['question'])
    return {'answer_b': text, 'time_b': secs}

def judge(state):
    a, b = state['answer_a'], state['answer_b']
    if a.startswith('ERROR:'):
        return {'winner': 'b', 'reason': 'Model A failed to answer.'}
    if b.startswith('ERROR:'):
        return {'winner': 'a', 'reason': 'Model B failed to answer.'}

    # show the answers in random order so the judge cannot favour 'first place'
    first, second = random.sample(['a', 'b'], 2)
    answers = {'a': a, 'b': b}
    prompt = (f"Question: {state['question']}\n\n"
              f"Answer 1:\n{answers[first]}\n\n"
              f"Answer 2:\n{answers[second]}\n\n"
              'Which answer is better? Judge accuracy, clarity and completeness.\n'
              'Reply in exactly this format:\n'
              'WINNER: 1 or 2\n'
              'REASON: one short sentence')
    try:
        text = ask(llm_judge, prompt)
    except Exception as e:
        return {'winner': 'a', 'reason': 'Judge failed (' + str(e)[:80] + '), defaulted to A.'}

    m = re.search(r'WINNER:\s*([12])', text)
    if m:
        pick = first if m.group(1) == '1' else second
    else:
        pick = 'a'
    r = re.search(r'REASON:\s*(.*)', text, re.S)
    reason = r.group(1).strip() if r else text.strip()
    return {'winner': pick, 'reason': reason}

def pick_a(state):
    return {'final': state['answer_a']}

def pick_b(state):
    return {'final': state['answer_b']}

def router(state):
    if state['winner'] == 'a':
        return 'pick_a'
    return 'pick_b'

from langgraph.graph import StateGraph, START, END

g = StateGraph(State)

g.add_node('model_a', model_a)
g.add_node('model_b', model_b)
g.add_node('judge', judge)
g.add_node('pick_a', pick_a)
g.add_node('pick_b', pick_b)

g.add_edge(START, 'model_a')
g.add_edge(START, 'model_b')
g.add_edge(['model_a', 'model_b'], 'judge')     # judge waits for BOTH
g.add_conditional_edges('judge', router, ['pick_a', 'pick_b'])
g.add_edge('pick_a', END)
g.add_edge('pick_b', END)

app = g.compile()

from IPython.display import Image, display
try:
    display(Image(app.get_graph().draw_mermaid_png()))
except Exception:
    print(app.get_graph().draw_mermaid())

import textwrap

def wrap(text):
    # wrap long lines so you don't have to scroll sideways
    return '\n'.join(textwrap.fill(p, 100) for p in text.split('\n'))

def compare(question):
    out = app.invoke({'question': question})
    print('QUESTION:', question, '\n')
    print(f"--- A: {MODEL_A} ({out['time_a']}s) ---\n{wrap(out['answer_a'])}\n")
    print(f"--- B: {MODEL_B} ({out['time_b']}s) ---\n{wrap(out['answer_b'])}\n")
    best = MODEL_A if out['winner'] == 'a' else MODEL_B
    print('WINNER :', best)
    print('REASON :', wrap(out['reason']))
    print('=' * 60)
    print('BEST ANSWER:\n' + wrap(out['final']))
    return out

_ = compare('Why did the chicken cross the road? Give a funny answer.')

import os, getpass, subprocess, sys

# Auto-install anything missing (so it works even if the pip cell above was skipped)
try:
    import langgraph, langchain_google_genai, langchain_groq, langchain_openai
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
                           'langgraph', 'langchain-google-genai', 'langchain-groq', 'langchain-openai'])

# ---- 1. Keys: paste between the quotes (easiest), or leave empty to use Colab Secrets / a prompt ----
GOOGLE_API_KEY = ""
GROQ_API_KEY = ""
THIRD_API_KEY = ""        # key for the fallback provider chosen below

# ---- 2. Which provider is the third (fallback) LLM?  "groq" | "cerebras" | "openrouter" | "mistral" ----
# "groq" needs NO new key (it reuses your Groq key and picks a different Groq model).
# For a fallback from a different company, create a key on that provider's website and set its name here.
THIRD_PROVIDER = "groq"

PROVIDERS = {
    'groq':       {'base_url': 'https://api.groq.com/openai/v1',     # reuses your Groq key, no new account
                   'prefer': ['qwen', 'gpt-oss-20b', 'allam']},
    'cerebras':   {'base_url': 'https://api.cerebras.ai/v1',
                   'prefer': ['llama-3.3-70b', 'gpt-oss-120b', 'llama3.1-8b', 'qwen']},
    'openrouter': {'base_url': 'https://openrouter.ai/api/v1',
                   'prefer': ['llama-3.3-70b', 'gpt-oss-120b', 'gemma', 'qwen', 'mistral']},
    'mistral':    {'base_url': 'https://api.mistral.ai/v1',
                   'prefer': ['mistral-small-latest', 'mistral-medium-latest', 'open-mistral-nemo']},
}

def get_key(value, secret_name):
    if not value:
        try:
            from google.colab import userdata
            value = userdata.get(secret_name)
        except Exception:
            value = getpass.getpass('Paste your ' + secret_name + ': ')
    return value.strip().strip('"').strip("'")

os.environ['GOOGLE_API_KEY'] = get_key(GOOGLE_API_KEY, 'GOOGLE_API_KEY')
os.environ['GROQ_API_KEY'] = get_key(GROQ_API_KEY, 'GROQ_API_KEY')
if THIRD_PROVIDER == 'groq' and not THIRD_API_KEY:
    os.environ['THIRD_API_KEY'] = os.environ['GROQ_API_KEY']      # reuse the Groq key
else:
    os.environ['THIRD_API_KEY'] = get_key(THIRD_API_KEY, 'THIRD_API_KEY')

# ---- 3. Model names. Leave "" to auto-pick from what YOUR keys can use, or type a name to force it ----
MODEL_A = "gemini-3.8-flash"   # Google Gemini
MODEL_B = ""                   # from Groq (auto: prefers Llama)
JUDGE_MODEL = ""               # from Groq (auto: a different model than MODEL_B)
MODEL_C = ""                   # fallback, from the THIRD_PROVIDER (auto)

skip = ('whisper', 'orpheus', 'guard', 'tts', 'safeguard', 'embed', 'image', 'video', 'audio', 'moderation')

def pick(preferred, available, avoid=()):
    for p in preferred:
        for m in available:
            if p in m and m not in avoid:
                return m
    for m in available:
        if m not in avoid:
            return m
    return None

# --- Groq: ask which models this key can use ---
try:
    from groq import Groq
    groq_models = sorted(m.id for m in Groq().models.list().data)
except Exception as e:
    groq_models = []
    print('Could not list Groq models:', str(e)[:150])
groq_chat = [m for m in groq_models if not any(s in m for s in skip)]
print('Groq chat models available:', groq_chat)

if not MODEL_B:
    MODEL_B = pick(['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'gpt-oss-20b'], groq_chat) or 'llama-3.3-70b-versatile'
if not JUDGE_MODEL:
    JUDGE_MODEL = pick(['gpt-oss-120b', 'llama-3.3-70b-versatile', 'gpt-oss-20b'], groq_chat, avoid=(MODEL_B,)) or MODEL_B

# --- Third provider: ask which models this key can use ---
prov = PROVIDERS[THIRD_PROVIDER]
try:
    from openai import OpenAI
    third_models = sorted(m.id for m in OpenAI(api_key=os.environ['THIRD_API_KEY'], base_url=prov['base_url']).models.list().data)
except Exception as e:
    third_models = []
    print('Could not list', THIRD_PROVIDER, 'models:', str(e)[:150])
    print('>>> FIX: THIRD_API_KEY must be a key created on the', THIRD_PROVIDER, 'website. Create one there,')
    print('>>> or change THIRD_PROVIDER above to match the provider your key is from.')
if THIRD_PROVIDER == 'openrouter':
    third_models = [m for m in third_models if m.endswith(':free')]
third_chat = [m for m in third_models if not any(s in m.lower() for s in skip)]
print(THIRD_PROVIDER, 'chat models available:', third_chat[:15])

if not MODEL_C:
    # if the fallback also comes from Groq, make sure it is a DIFFERENT model than B and the judge
    avoid = (MODEL_B, JUDGE_MODEL) if THIRD_PROVIDER == 'groq' else ()
    MODEL_C = pick(prov['prefer'], third_chat, avoid=avoid) or prov['prefer'][0]

# --- Create the 4 model objects ---
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI

llm_a = ChatGoogleGenerativeAI(model=MODEL_A, timeout=30, max_retries=1)
llm_b = ChatGroq(model=MODEL_B, timeout=30, max_retries=1)
llm_judge = ChatGroq(model=JUDGE_MODEL, timeout=30, max_retries=1)
llm_c = ChatOpenAI(model=MODEL_C, api_key=os.environ['THIRD_API_KEY'], base_url=prov['base_url'], timeout=30, max_retries=1)

print('Ready -> A:', MODEL_A, '| B:', MODEL_B, '| fallback C:', MODEL_C, '| judge:', JUDGE_MODEL)

def health(label, llm):
    try:
        llm.invoke('Reply with the single word: OK')
        print('  OK    ', label)
    except Exception as e:
        print('  FAIL  ', label, '->', str(e)[:130])

print('Health check:')
health('A (Gemini)      ' + MODEL_A, llm_a)
health('B (Groq)        ' + MODEL_B, llm_b)
health('C (fallback)    ' + MODEL_C, llm_c)
health('Judge (Groq)    ' + JUDGE_MODEL, llm_judge)

import operator
from typing import TypedDict, Annotated

class State(TypedDict):
    question: str
    answer_a: str     # answer in slot A
    answer_b: str     # answer in slot B
    time_a: float     # seconds slot A took
    time_b: float
    ok_a: bool        # did slot A produce a real answer?
    ok_b: bool
    who_a: str        # which model produced slot A (changes if the fallback takes over)
    who_b: str
    winner: str       # 'a' or 'b'
    reason: str       # why the judge chose it
    final: str        # the best answer
    log: Annotated[list, operator.add]   # every node can add messages to this list

import time, re, random, textwrap

# Set to "a", "b" or "both" to TEST the fallback by faking an outage (section 8 does this for you)
SIMULATE_FAIL = ""

def ask(llm, prompt):
    # always returns plain text (some models return a list of blocks)
    content = llm.invoke(prompt).content
    if isinstance(content, list):
        return ''.join(b if isinstance(b, str) else b.get('text', '') for b in content)
    return content

def run_model(llm, question, simulate=False):
    # Calls one model and returns (text, seconds, ok). It never crashes the graph:
    # any problem just sets ok=False so the router can switch to the fallback.
    start = time.time()
    try:
        if simulate:
            raise RuntimeError('Simulated outage (503 Service Unavailable)')
        text = ask(llm, question)
        if not text.strip():
            raise RuntimeError('Model returned an empty answer')
        ok = True
    except Exception as e:
        # <<< THE FAILURE IS CAUGHT HERE: rate limit, bad key, wrong model name, timeout, empty answer...
        text = 'ERROR: ' + str(e)[:200]
        ok = False
    return text, round(time.time() - start, 1), ok

def model_a(state):
    text, secs, ok = run_model(llm_a, state['question'], SIMULATE_FAIL in ('a', 'both'))
    if ok:
        msg = 'Model A (' + MODEL_A + ') answered in ' + str(secs) + 's'
    else:
        msg = 'Model A (' + MODEL_A + ') FAILED -> ' + text
    return {'answer_a': text, 'time_a': secs, 'ok_a': ok, 'who_a': MODEL_A, 'log': [msg]}

def model_b(state):
    text, secs, ok = run_model(llm_b, state['question'], SIMULATE_FAIL in ('b', 'both'))
    if ok:
        msg = 'Model B (' + MODEL_B + ') answered in ' + str(secs) + 's'
    else:
        msg = 'Model B (' + MODEL_B + ') FAILED -> ' + text
    return {'answer_b': text, 'time_b': secs, 'ok_b': ok, 'who_b': MODEL_B, 'log': [msg]}

def check(state):
    if state['ok_a'] and state['ok_b']:
        msg = 'Check: both models answered, no fallback needed'
    else:
        msg = 'Check: a model failed, the fallback model must step in'
    return {'log': [msg]}

def fallback(state):
    # <<< THE SWITCH HAPPENS HERE: the third model answers in place of the failed one
    text, secs, ok = run_model(llm_c, state['question'])
    both_failed = (not state['ok_a']) and (not state['ok_b'])
    if not state['ok_a']:
        slot, failed = 'a', state['who_a']
    else:
        slot, failed = 'b', state['who_b']
    update = {'answer_' + slot: text, 'time_' + slot: secs, 'ok_' + slot: ok, 'who_' + slot: MODEL_C}
    status = ('answered in ' + str(secs) + 's') if ok else ('FAILED too -> ' + text)
    note = 'SWITCH: ' + failed + ' failed, so fallback ' + MODEL_C + ' took its place (' + status + ')'
    if both_failed:
        note += ' | both A and B failed, so the fallback answers alone'
    update['log'] = [note]
    return update

def judge(state):
    a_ok, b_ok = state['ok_a'], state['ok_b']
    if (not a_ok) and (not b_ok):
        return {'winner': 'a', 'reason': 'No model could answer.', 'log': ['Judge: every model failed, nothing to judge']}
    if not a_ok:
        return {'winner': 'b', 'reason': state['who_a'] + ' failed to answer.', 'log': ['Judge: only slot B has an answer']}
    if not b_ok:
        return {'winner': 'a', 'reason': state['who_b'] + ' failed to answer.', 'log': ['Judge: only slot A has an answer']}

    # show the answers in random order so the judge cannot favour 'first place'
    first, second = random.sample(['a', 'b'], 2)
    answers = {'a': state['answer_a'], 'b': state['answer_b']}
    q = state['question']
    prompt = ('Question: ' + q + '\n\n'
              'Answer 1:\n' + answers[first] + '\n\n'
              'Answer 2:\n' + answers[second] + '\n\n'
              'Which answer is better? Judge accuracy, clarity and completeness.\n'
              'Reply in exactly this format:\n'
              'WINNER: 1 or 2\n'
              'REASON: one short sentence')
    text = None
    for j in (llm_judge, llm_c):          # if the judge model is down, the fallback model judges instead
        try:
            text = ask(j, prompt)
            break
        except Exception:
            continue
    if text is None:
        return {'winner': 'a', 'reason': 'Judge unavailable, defaulted to A.', 'log': ['Judge: no judge model available']}

    m = re.search(r'WINNER:\s*([12])', text)
    if m:
        pick_slot = first if m.group(1) == '1' else second
    else:
        pick_slot = 'a'
    r = re.search(r'REASON:\s*(.*)', text, re.S)
    reason = r.group(1).strip() if r else text.strip()
    return {'winner': pick_slot, 'reason': reason, 'log': ['Judge picked slot ' + pick_slot.upper()]}

def pick_a(state):
    return {'final': state['answer_a']}

def pick_b(state):
    return {'final': state['answer_b']}

def failure_router(state):
    # <<< THE DECISION TO SWITCH: if a model failed, route to the fallback node
    if state['ok_a'] and state['ok_b']:
        return 'judge'
    return 'fallback'

def winner_router(state):
    if state['winner'] == 'a':
        return 'pick_a'
    return 'pick_b'

from langgraph.graph import StateGraph, START, END

g = StateGraph(State)

g.add_node('model_a', model_a)
g.add_node('model_b', model_b)
g.add_node('check', check)
g.add_node('fallback', fallback)
g.add_node('judge', judge)
g.add_node('pick_a', pick_a)
g.add_node('pick_b', pick_b)

g.add_edge(START, 'model_a')
g.add_edge(START, 'model_b')
g.add_edge(['model_a', 'model_b'], 'check')                          # check waits for BOTH
g.add_conditional_edges('check', failure_router, ['fallback', 'judge'])
g.add_edge('fallback', 'judge')
g.add_conditional_edges('judge', winner_router, ['pick_a', 'pick_b'])
g.add_edge('pick_a', END)
g.add_edge('pick_b', END)

app = g.compile()

from IPython.display import Image, display
try:
    display(Image(app.get_graph().draw_mermaid_png()))
except Exception:
    print(app.get_graph().draw_mermaid())

def wrap(text):
    # wrap long lines so you don't have to scroll sideways
    return '\n'.join(textwrap.fill(p, 100) for p in text.split('\n'))

def compare(question, simulate=""):
    global SIMULATE_FAIL
    SIMULATE_FAIL = simulate
    try:
        out = app.invoke({'question': question, 'log': []})
    finally:
        SIMULATE_FAIL = ""
    print('QUESTION:', question, '\n')
    print('WHAT HAPPENED:')
    for line in out['log']:
        print('  -', line)
    print()
    print('--- Slot A: ' + out['who_a'] + ' (' + str(out['time_a']) + 's) ---\n' + wrap(out['answer_a']) + '\n')
    print('--- Slot B: ' + out['who_b'] + ' (' + str(out['time_b']) + 's) ---\n' + wrap(out['answer_b']) + '\n')
    best = out['who_a'] if out['winner'] == 'a' else out['who_b']
    print('WINNER :', best)
    print('REASON :', wrap(out['reason']))
    print('=' * 60)
    print('BEST ANSWER:\n' + wrap(out['final']))
    return out

_ = compare('who am i')